### Don't initialize zero as a parameters.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/ushape.csv')

In [ ]:
df.head()

X         Y  class
0  0.031595  0.986988    0.0
1  2.115098 -0.046244    1.0
2  0.882490 -0.075756    0.0
3 -0.055144 -0.037332    1.0
4  0.829545 -0.539321    1.0

In [ ]:
X = df.iloc[:,:2]
y = df.iloc[:,-1]

In [ ]:
X.head()

X         Y
0  0.031595  0.986988
1  2.115098 -0.046244
2  0.882490 -0.075756
3 -0.055144 -0.037332
4  0.829545 -0.539321

In [ ]:
y.head()

0    0.0
1    1.0
2    0.0
3    1.0
4    1.0
Name: class, dtype: float64

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In hidden layer,the activation function is sigmoid

In [ ]:
model = Sequential()

model.add(Dense(10,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41 (164.00 B)

 Trainable params: 41 (164.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# default parameters value
initial_weights = model.get_weights()

In [ ]:
initial_weights

[array([[-0.5733463 ,  0.64458984,  0.49443847, -0.21036336,  0.2561574 ,
         -0.08302796,  0.09272206,  0.45627135,  0.15160173,  0.35259193],
        [ 0.3713233 , -0.3173597 , -0.50246274, -0.47208953,  0.10728854,
         -0.46829683,  0.28216338, -0.66049486, -0.30119926,  0.1409055 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.23958403],
        [ 0.30826455],
        [-0.01683992],
        [ 0.6349562 ],
        [ 0.72181696],
        [ 0.11591262],
        [-0.24463567],
        [-0.5701653 ],
        [ 0.22358555],
        [-0.32244903]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
initial_weights[0] = np.zeros(model.get_weights()[0].shape)
initial_weights[1] = np.zeros(model.get_weights()[1].shape)
initial_weights[2] = np.zeros(model.get_weights()[2].shape)
initial_weights[3] = np.zeros(model.get_weights()[3].shape)

In [ ]:
model.set_weights(initial_weights)

In [ ]:
model.get_weights()

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
history = model.fit(X,y,epochs=100,validation_split=0.2)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.6739 - val_accuracy: 0.5000 - val_loss: 0.6679
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4766 - loss: 0.6798 - val_accuracy: 0.5000 - val_loss: 0.6672
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5039 - loss: 0.6728 - val_accuracy: 0.5000 - val_loss: 0.6663
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5234 - loss: 0.6699 - val_accuracy: 0.5000 - val_loss: 0.6654
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5312 - loss: 0.6668 - val_accuracy: 0.5000 - val_loss: 0.6646
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4766 - loss: 0.6803 - val_accuracy: 0.5000 - val_loss: 0.6639
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4922 - loss: 0.6737 - val_accuracy: 0.5000 - val_loss: 0.6631
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4609 - loss: 0.6819 - val_accuracy: 0.5000 - val_loss:

In [ ]:
model.get_weights()

[array([[ 0.8165898 ,  0.8165898 ,  0.8165898 ,  0.8165898 ,  0.8165898 ,
          0.8165898 ,  0.8165898 ,  0.8165898 ,  0.8165898 ,  0.8165898 ],
        [-0.98941016, -0.98941016, -0.98941016, -0.98941016, -0.98941016,
         -0.98941016, -0.98941016, -0.98941016, -0.98941016, -0.98941016]],
       dtype=float32),
 array([-0.48637223, -0.48637223, -0.48637223, -0.48637223, -0.48637223,
        -0.48637223, -0.48637223, -0.48637223, -0.48637223, -0.48637223],
       dtype=float32),
 array([[0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798],
        [0.15729798]], dtype=float32),
 array([-0.28637463], dtype=float32)]

In [ ]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X=X.values,y=y.values.astype(int),clf=model,legend=2)
plt.show()

9600/9600 ━━━━━━━━━━━━━━━━━━━━ 11s 1ms/step
